version: "3.8"

services:

  proposta_api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: lbovolini/proposta-api
    container_name: proposta-api
    ports:
      - "8081:8080"
    environment:
      PROPOSTA_DB_HOSTNAME: proposta-db
      PROPOSTA_DB_PORT: 5432
      PROPOSTA_DB_USERNAME: ${PROPOSTA_DB_USERNAME}
      PROPOSTA_DB_PASSWORD: ${PROPOSTA_DB_PASSWORD}
    networks:
      - proposta-network
    depends_on:
      - proposta_db


  proposta_db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${PROPOSTA_DB_USERNAME}
      POSTGRES_PASSWORD: ${PROPOSTA_DB_PASSWORD}
      POSTGRES_DB: ${PROPOSTA_DB_NAME}
    container_name: proposta-db
    hostname: proposta-db
    ports:
      - "5432:5432"
    networks:
      - proposta-network
    volumes:
      - ./db:/usr/local/pgsql/data

networks:
  proposta-network:
    driver: bridge
